version: '2'

services:
  xrdp:
    build:
      context: ./
      args:
        USER: mary
        PASSWORD: mary
        UID: 1001
        GID: 1001
    ports:
      - "33891:3389"
#   volumes:
#     - ./data/:/home/${USER}/
#   environment:
