version: '2'

services:
  xrdp:
    build:
      context: ./
      args:
        USER: mary
        PASSWORD: mary
        # set your uid, gid on the host
        UID: 1000
        GID: 1000
        http_proxy:
        https_proxy:
    ports:
      - "33891:3389"
